theme: jekyll-theme-minimal
title: Title from config
description: Description from config
plugins:
  - jekyll-optional-front-matter

defaults:
  - scope:
      path: ""          # Applies to all files
      type: "pages"     # Applies to all Markdown pages
    values:
      layout: "default"

